push

diff --git a/basics_1/0-change_your_home_IP b/basics_1/0-change_your_home_IP
--- a/basics_1/0-change_your_home_IP
+++ b/basics_1/0-change_your_home_IP
@@ -1,20 +1,21 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Script to configure an Ubuntu server with specific IP addresses
+# - Changes localhost to resolve to 127.0.0.2
+# - Changes facebook.com to resolve to 8.8.8.8
 
-# Make a copy of the hosts file
+# Create a new hosts file
 cp /etc/hosts ~/hosts.new
 
-# Replace localhost IP with 127.0.0.2
-sed -i 's/127.*localhost/127.0.0.2 localhost/g' ~/hosts.new
+# Update the localhost entry
+sed -i 's/127[.][0-9.]*[[:space:]]localhost$/127.0.0.2 localhost/' ~/hosts.new
+grep -q "127.0.0.2 localhost" ~/hosts.new || echo "127.0.0.2 localhost" >> ~/hosts.new
 
-# Add facebook.com entry (or replace if exists)
-if grep -q "facebook.com" ~/hosts.new; then
-    sed -i 's/.*facebook.com/8.8.8.8 facebook.com/g' ~/hosts.new
-else
-    echo "8.8.8.8 facebook.com" >> ~/hosts.new
-fi
+# Update the facebook.com entry
+sed -i '/facebook\.com$/d' ~/hosts.new
+echo "8.8.8.8 facebook.com" >> ~/hosts.new
 
-# Copy the modified file back to /etc/hosts
+# Replace the original hosts file
 cp -f ~/hosts.new /etc/hosts
 
-# Clean up the temporary file
-rm ~/hosts.new
+# Clean up
+rm -f ~/hosts.new
